---
- name: create users using a loop from a list
  hosts: hap01
  vars_files: ../vars/users
  tasks:
  - name: create users
    user:
      name: "{{ item.username }}"
      state: present
      groups: "{{ item.groups }}"
      shell: "{{ item.shell }}"
    loop: "{{ users }}"