---
- name: test if variable is in another variables list
  hosts: hap
  vars_prompt:
  - name: my_answer
    prompt: which package do you want to install
  vars:
    supported_packages:
      - httpd
      - keepalived
  tasks:
   - name: Check requested packages allowed
     debug:
       msg: you are trying to install a supported package
     when: my_answer in supported_packages