---
- name: demonstrating the fail module
  hosts: hap
  ignore_errors: true
  tasks:
  - name: run a script
    command: echo world
    register: command_result
  - name: report a failure
    fail:
      msg: the command has failed
    when: "'world' in command_result.stdout"
  - name: see if we get here
    debug:
      msg: second task executed