---
- name: Pre upgrades check
  hosts: hap
  tasks:
  - name: Configuration check with current version
    command: haproxy -c -f /etc/haproxy/.
    register: command_result
    changed_when: false

  - name: Configuration check result with current version
    debug:
      var: command_result.stdout

  - name: Configuration check with HAP 2.6.15
    command: ~/haproxy-2.6.15/haproxy -c -f /etc/haproxy/.
    register: command_result
    changed_when: false

  - name: Configuration check result version 2.6.15
    debug:
      var: command_result.stdout
    failed_when: 
      - "'ALERT' in command_result.stdout"