---
- name: HAProxy Upgrades - Pre-Check
  hosts: hapnodns
  vars_files:
    - "../vars/app.yml"
    - "../vars/backendServers.yml"
  tasks:
  - name: Deploy HAP Configuration file
    template:
      src: ../templates/haproxy.cfg.j2
      dest: /tmp/haproxy.cfg


    