---
webapp:
  - frontend_name: myFirstFrontEnd
    backend_name: myFirstBackEnd
    frontend_port: 8080
    backend_port: 3000 
    backend_servers: 
      - server: 192.168.100.210
      - server: 192.168.100.211
      - server: 192.168.100.212
    
  - frontend_name: mySecondFrontEnd
    backend_name: mySecondBackEnd
    frontend_port: 8081
    backend_port: 3001
    backend_servers: 
      - server: 192.168.100.210
      - server: 192.168.100.211
      - server: 192.168.100.212