---
- name: install start and enable httpd
  hosts: hap
  tasks:
   - name: install package
     yum:
      name: 
        - haproxy
        - keepalived
        - make
      state: installed
    
   - name: stop firewalld
     service:
      name: firewalld
      state: stopped
      enabled: no

   - name: start and enable haproxy service
     service:
      name: haproxy 
      state: started
      enabled: yes

   - name: start and enable keepalived service
     service:
      name: keepalived
      state: started
      enabled: yes