---
- name: install start and enable httpd
  hosts: all
  tasks:
   - name: install package
     yum:
      name: httpd
      state: installed

   - name: start and enable service
     service:
      name: httpd
      state: started
      enabled: yes